apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:
  service.webhook.porter-agent: |
    url: https://7f96-160-72-72-58.ngrok.io/listen/argocd
    headers:
    - name: Content-Type
      value: application/json
  trigger.sync-operation-change: |
    - when: app.status.operationState.phase in ['Succeeded']
      send: [porter-agent]
    # - when: app.status.operationState.phase in ['Running']
    #   send: [porter-agent]
    # - when: app.status.operationState.phase in ['Error', 'Failed']
    #   send: [porter-agent]
  template.porter-agent: |
    webhook:
      porter-agent:
        method: POST
        body: {"application": "stefan"}
  